export const SYSTEM_PROMPT = `你是 AnswerCanvas 的内容规划器。请回答用户问题，并把答案整理成一张自然、克制、像人边思考边写出来的手写画布。
规则：
1. 只输出 JSON，不输出 HTML、SVG、Markdown 或像素坐标。
2. 内容以帮助读者理解和行动为目标，避免空泛结论和资料堆砌。
3. 优先采用“一个核心结论 + 2–4 个必要信息块”的结构，不要机械地把每个问题都写成标题、三条列表、流程图、总结框。
4. title 应像自然的开场结论，而不是报告标题；正文尽量短句、留白充足。
5. 需要强调时，把关键词单独拆成 span，再用 highlight、circle、underline 或 strike 标注；不要给整段文字加标注。
6. 流程图只表达真实步骤，图表只在存在真实可比较数据时使用。没有数据时不要编造图表。
7. 图形应承担解释关系的作用：趋势用 line-chart，步骤用 flow-diagram，对立关系用 comparison。
8. 不生成 question 字段。用户原始问题由服务端注入。
9. 所有 ID 在各自作用域唯一。`;

const id = { type: "string", minLength: 1, maxLength: 120 } as const;
const span = { type: "object", additionalProperties: false, required: ["id", "text", "emphasis"], properties: { id, text: { type: "string", minLength: 1, maxLength: 240 }, emphasis: { anyOf: [{ type: "string", enum: ["normal", "strong"] }, { type: "null" }] } } } as const;
const annotation = { type: "object", additionalProperties: false, required: ["id", "type", "target"], properties: { id, type: { type: "string", enum: ["highlight", "circle", "underline", "strike"] }, target: { type: "object", additionalProperties: false, required: ["blockId", "spanId"], properties: { blockId: id, spanId: id } } } } as const;
const textBlock = { type: "object", additionalProperties: false, required: ["type", "id", "spans", "annotations"], properties: { type: { const: "text" }, id, spans: { type: "array", minItems: 1, maxItems: 12, items: span }, annotations: { type: "array", maxItems: 20, items: annotation } } } as const;
const bulletBlock = { type: "object", additionalProperties: false, required: ["type", "id", "items", "annotations"], properties: { type: { const: "bullet-list" }, id, items: { type: "array", minItems: 1, maxItems: 8, items: { type: "object", additionalProperties: false, required: ["id", "spans"], properties: { id, spans: { type: "array", minItems: 1, maxItems: 12, items: span } } } }, annotations: { type: "array", maxItems: 20, items: annotation } } } as const;
const comparisonBlock = { type: "object", additionalProperties: false, required: ["type", "id", "left", "right"], properties: { type: { const: "comparison" }, id, left: { type: "object", additionalProperties: false, required: ["title", "items"], properties: { title: { type: "string", minLength: 1, maxLength: 80 }, items: { type: "array", minItems: 1, maxItems: 8, items: { type: "string", minLength: 1, maxLength: 160 } } } }, right: { type: "object", additionalProperties: false, required: ["title", "items"], properties: { title: { type: "string", minLength: 1, maxLength: 80 }, items: { type: "array", minItems: 1, maxItems: 8, items: { type: "string", minLength: 1, maxLength: 160 } } } } } } as const;
const flowBlock = { type: "object", additionalProperties: false, required: ["type", "id", "nodes", "edges"], properties: { type: { const: "flow-diagram" }, id, nodes: { type: "array", minItems: 2, maxItems: 8, items: { type: "object", additionalProperties: false, required: ["id", "label"], properties: { id, label: { type: "string", minLength: 1, maxLength: 80 } } } }, edges: { type: "array", minItems: 1, maxItems: 12, items: { type: "object", additionalProperties: false, required: ["from", "to", "label"], properties: { from: id, to: id, label: { anyOf: [{ type: "string", minLength: 1, maxLength: 60 }, { type: "null" }] } } } } } } as const;
const chartBlock = { type: "object", additionalProperties: false, required: ["type", "id", "title", "labels", "series"], properties: { type: { const: "line-chart" }, id, title: { anyOf: [{ type: "string", minLength: 1, maxLength: 80 }, { type: "null" }] }, labels: { type: "array", minItems: 2, maxItems: 30, items: { type: "string", minLength: 1, maxLength: 30 } }, series: { type: "array", minItems: 1, maxItems: 3, items: { type: "object", additionalProperties: false, required: ["id", "name", "color", "points"], properties: { id, name: { type: "string", minLength: 1, maxLength: 40 }, color: { type: "string", enum: ["blue", "green"] }, points: { type: "array", minItems: 2, maxItems: 30, items: { type: "number" } } } } } } } as const;
const calloutBlock = { type: "object", additionalProperties: false, required: ["type", "id", "tone", "spans", "annotations"], properties: { type: { const: "callout" }, id, tone: { type: "string", enum: ["idea", "warning", "summary"] }, spans: { type: "array", minItems: 1, maxItems: 12, items: span }, annotations: { type: "array", maxItems: 20, items: annotation } } } as const;
const endpoint = { type: "object", additionalProperties: false, required: ["blockId", "anchor"], properties: { blockId: id, anchor: { type: "string", enum: ["top", "right", "bottom", "left", "center"] } } } as const;
export const RAW_AI_JSON_SCHEMA = { type: "object", additionalProperties: false, required: ["answer", "note"], properties: { answer: { type: "string", minLength: 1, maxLength: 6000 }, note: { type: "object", additionalProperties: false, required: ["id", "title", "blocks", "arrows", "truncated"], properties: { id, title: { type: "string", minLength: 1, maxLength: 80 }, blocks: { type: "array", minItems: 1, maxItems: 12, items: { anyOf: [textBlock, bulletBlock, comparisonBlock, flowBlock, chartBlock, calloutBlock] } }, arrows: { type: "array", maxItems: 8, items: { type: "object", additionalProperties: false, required: ["id", "type", "from", "to", "label"], properties: { id, type: { const: "arrow" }, from: endpoint, to: endpoint, label: { anyOf: [{ type: "string", minLength: 1, maxLength: 60 }, { type: "null" }] } } } }, truncated: { type: "boolean" } } } } } as const;
